nodeLinker: node-modules

packageExtensions:
  "@firebase/auth-interop-types@*":
    dependencies:
      "@firebase/app-types": "*"
  recharts@*:
    dependencies:
      prop-types: "*"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
