[package]
name = "fleethub-core"
version = "1.2.1"
authors = ["まどの <madonoharu@gmail.com>"]
edition = "2021"
description = "fleethub-core"
repository = "https://github.com/madonoharu/fleethub"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
js-sys = "0.3.56"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
#
# Unfortunately, `wee_alloc` requires nightly Rust when targeting wasm for now.
wee_alloc = { version = "0.4.5", optional = true }
strum = { version = "0.24.0", features = ["derive"] }
num-traits = "0.2.14"
num-derive = "0.3.3"
num_enum = "0.5.7"
fasteval = "0.2.4"
paste = "1.0.7"
arrayvec = { version = "0.7.2", features = ["serde"] }
counter = "0.5.3"
rand = { version = "0.8.5", features = ["small_rng"] }
getrandom = { version = "0.2.6", features = ["js"] }
xxhash-rust = { version = "0.8.4", features = ["xxh3"] }
enumset = "1.0.8"
anyhow = "1.0.56"
thiserror = "1.0.30"
itertools = "0.10.3"
enum-map = "2.1.0"
seq-macro = "0.3.0"
tsify = "0.1.1"

[dependencies.web-sys]
version = "0.3.56"
features = ["console"]

[dev-dependencies]
wasm-bindgen-test = "0.3.29"
criterion = "0.3.5"
reqwest = { version = "0.11.10", features = ["brotli"] }
tokio = { version = "1.17.0", features = ["full"] }
once_cell = "1.10.0"

[[bench]]
name = "bench"
harness = false
