[package]
name = "fleethub-core"
version = "1.8.4"
authors = ["まどの <madonoharu@gmail.com>"]
edition = "2021"
description = "fleethub-core"
repository = "https://github.com/madonoharu/fleethub"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "0.2.82", features = ["serde-serialize"] }
js-sys = "0.3.59"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
serde_with = "2.0.0"
rand = { version = "0.8.5", features = ["small_rng"] }
getrandom = { version = "0.2.7", features = ["js"] }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.7", optional = true }

anyhow = "1.0.62"
thiserror = "1.0.32"
arrayvec = { version = "0.7.2", features = ["serde"] }
hashbrown = { version = "0.12.3", features = ["serde"] }
enumset = "1.0.11"
enum-map = "2.4.1"
num-traits = "0.2.15"
num-derive = "0.3.3"
strum = { version = "0.24.1", features = ["derive"] }
itertools = "0.10.3"
seq-macro = "0.3.1"
paste = "1.0.8"
tsify = "0.3.1"
fasteval = "0.2.4"
ordered-float = { version = "3.0.0", features = ["serde"] }

[dependencies.web-sys]
version = "0.3.59"
features = ["console"]

[dev-dependencies]
wasm-bindgen-test = "0.3.32"
criterion = "0.3.6"
once_cell = "1.13.1"
toml_edit = { version = "*", features = ["easy"] }
assert-json-diff = "2.0.2"
walkdir = "2"
fleethub-core-test = { path = "../fleethub-core-test" }

[[bench]]
name = "bench"
harness = false
